# Generated by Django 5.1 on 2024-09-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='estado',
            field=models.CharField(choices=[('INI', 'Iniciada'), ('TER', 'Terminada'), ('CAN', 'Cancelada')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PEN', 'Pendiente'), ('PRO', 'Procesando'), ('COM', 'Completado'), ('CAN', 'Cancelado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='estado',
            field=models.CharField(choices=[('PEN', 'Pendiente'), ('CONF', 'Confirmada'), ('CAN', 'Cancelada')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='id_partida',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='id_pedido',
        ),
        migrations.AlterField(
            model_name='pistabowling',
            name='estado',
            field=models.CharField(choices=[('DIS', 'Disponible'), ('OCU', 'Ocupada'), ('MAN', 'Mantenimiento')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('PEN', 'Pendiente'), ('CONF', 'Confirmada'), ('CAN', 'Cancelada')], max_length=20),
        ),
        migrations.DeleteModel(
            name='EstadoPartida',
        ),
        migrations.DeleteModel(
            name='EstadoPedido',
        ),
        migrations.DeleteModel(
            name='EstadoReserva',
        ),
    ]
