# Generated by Django 5.1 on 2024-09-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_cliente_mail_cliente_email_cliente_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
