# Generated by Django 5.1 on 2024-09-26 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_cliente_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='is_staff',
        ),
    ]
