# Generated by Django 5.1 on 2024-10-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_reserva_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='cant_jugadores',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
