# Generated by Django 5.1 on 2024-10-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_reserva_id_partida_remove_reserva_id_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_hora_reserva',
            field=models.DateTimeField(),
        ),
    ]
