# Generated by Django 5.1 on 2024-10-12 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_reserva_fecha_hora_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pistabowling',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.estadopista'),
        ),
    ]
