# Generated by Django 5.1 on 2024-10-26 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_reserva_fecha_hora_fin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='id_producto',
        ),
    ]
