classDiagram
    direction LR

    class Cliente {
        +id_cliente: AutoField
        +email: EmailField
        +nombre: CharField
        +direccion: CharField
        +telefono: CharField
        +password: CharField
        +is_staff: BooleanField
        +is_active: BooleanField
        +is_superuser: BooleanField
        +create_user()
        +create_superuser()
    }

    class PistaBowling {
        +id_pista: AutoField
        +capacidad_maxima: IntegerField
        +descripcion: CharField
        +estado: ForeignKey
    }

    class Reserva {
        +id_reserva: AutoField
        +id_cliente: ForeignKey
        +id_pista: ForeignKey
        +fecha_hora_reserva: DateTimeField
        +fecha_hora_fin: TimeField
        +save()
        +crear_historial_estado_inicial()
        +procesar_reserva()
        +actualizar_ultimo_estado()
        +verificar_confirmacion()
        +verificar_estado_actual()
        +verificar_finalizacion()
        +actualizar_fecha_hora_fin()
        +crear_historial_estado()
        +finalizar()
        +estado_actual: property
    }

    class EstadoReserva {
        +estado: CharField
        +descripcion: CharField
    }

    class Jugador {
        +id_jugador: AutoField
        +id_partida: ForeignKey
        +nombre_jugador: CharField
        +orden: IntegerField
        +puntaje_total: property
    }

    class Partida {
        +id_partida: AutoField
        +id_pista: ForeignKey
        +id_reserva: ForeignKey
        +estado: ForeignKey
        +cant_jugadores: IntegerField
        +ganador: ForeignKey
        +actualizar_estado()
        +crear_partidas_para_reserva()
        +actualizar_estado_partida()
        +calcular_ganador()
        +get_current_turn()
        +is_game_finished()
        +finalize_game()
        +crear_turnos()
        +iniciar_partida()
    }

    class EstadoPartida {
        +estado: CharField
        +descripcion: CharField
    }

    class Turno {
        +numero_turno: AutoField
        +id_partida: ForeignKey
        +orden: CharField
        +ultimo_turno: BooleanField
    }

    class Tirada {
        +numero_tirada: AutoField
        +pinos_deribados: IntegerField
        +orden: IntegerField
        +id_jugador: ForeignKey
        +numero_turno: ForeignKey
        +registrar_tirada()
    }

    class EstadoPista {
        +estado: CharField
        +descripcion: CharField
    }

    class Pedido {
        +id_pedido: AutoField
        +estado: ForeignKey
        +fecha_hora_pedido: DateField
        +id_reserva: ForeignKey
        +total_a_pagar: property
        +crear_pedido()
    }

    class EstadoPedido {
        +estado: CharField
        +descripcion: CharField
    }

    class PedidoXProducto {
        +id_pedido: ForeignKey
        +id_producto: ForeignKey
        +cantidad: IntegerField
    }

    class Producto {
        +id_producto: AutoField
        +nombre: CharField
        +descripcion: CharField
        +precio: IntegerField
    }

    class HistorialEstado {
        +id_reserva: ForeignKey
        +estado: ForeignKey
        +fecha_hora_inicio: DateTimeField
        +fecha_hora_fin: DateTimeField
    }



    Cliente --> "*" Reserva

    Reserva --> "1" HistorialEstado
    Reserva  --> "1" PistaBowling
    Reserva --> "*" Pedido
    Reserva --> "*" Partida

    HistorialEstado --> "*" EstadoReserva

    Pedido --> "1" EstadoPedido
    Pedido -- "1" PedidoXProducto
    PedidoXProducto  --> "*" Producto

    PistaBowling --> "1" Partida
    PistaBowling --> "1" EstadoPista

    Partida --> "*" Jugador
    Partida --> "*" Turno
    Partida --> "1" EstadoPartida

    Jugador --> "*" Tirada

    Turno --> "*" Tirada


