DROP DATABASE IF EXISTS BOWLING;
CREATE DATABASE IF NOT EXISTS BOWLING;
USE BOWLING;

CREATE TABLE CLIENTES ( 
    ID_CLIENTE INT,
    NOMBRE VARCHAR(60),
    DIRECCION VARCHAR(120),
    TELEFONO VARCHAR(20),
    MAIL VARCHAR(60),
    PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE RESERVAS ( 
    ID_CLIENTE INT,
    ID_PISTA INT,
    FECHA_HORA_RESERVA DATE,
    ID_RESERVA INT,
    ID_PARTIDA INT,
    ID_PEDIDO INT,
    ESTADO VARCHAR(20),
    PRIMARY KEY (ID_RESERVA)
    
);

CREATE TABLE ESTADOS_RESERVAS ( 
    ESTADO VARCHAR(20),
    DESCRIPCION VARCHAR(240),
    PRIMARY KEY (ESTADO)
);

CREATE TABLE JUGADORES ( 
    ID_JUGADOR INT,
    ID_PARTIDA INT,
    NOMBRE_JUGADOR VARCHAR(10),
    ORDEN INT,
    PRIMARY KEY (ID_JUGADOR, ID_PARTIDA)
    
);

CREATE TABLE PARTIDAS ( 
    ID_PARTIDA INT,
    ID_PISTA INT,
    ID_RESERVA INT,
    ESTADO VARCHAR(20),
    PRIMARY KEY (ID_PARTIDA)
    
);

CREATE TABLE ESTADOS_PARTIDAS ( 
    ESTADO VARCHAR(20),
    DESCRIPCION VARCHAR(240),
    PRIMARY KEY (ESTADO)
);

CREATE TABLE TURNOS ( 
    NUMERO_TURNO INT,
    ID_PARTIDA INT,
    ORDEN varchar(20),
    ULTIMO_TURNO BOOLEAN,
    PRIMARY KEY (NUMERO_TURNO)
);

CREATE TABLE TIRADAS ( 
    NUMERO_TIRADA INT,
    PINOS_DERIBADOS INT,
    ORDEN INT,
    ID_JUGADOR INT,
    NUMERO_TURNO INT,
    PRIMARY KEY (NUMERO_TIRADA)
);

CREATE TABLE PISTAS_BOWLING ( 
    ID_PISTA INT,
    CAPACIDAD_MAXIMA INT,
    DESCRIPCION VARCHAR(240),
    ESTADO VARCHAR(20),
    PRIMARY KEY (ID_PISTA)
    
);

CREATE TABLE ESTADOS_PISTAS ( 
    ESTADO VARCHAR(20),
    DESCRIPCION VARCHAR(240),
    PRIMARY KEY (ESTADO)
);

CREATE TABLE PEDIDOS ( 
    ID_PEDIDO INT,
    ID_PRODUCTO INT,
    ESTADO VARCHAR(20),
    FECHA_HORA_PEDIDO DATE,
    PRIMARY KEY (ID_PEDIDO)
    
);

CREATE TABLE ESTADOS_PEDIDOS ( 
    ESTADO VARCHAR(20),
    DESCRIPCION VARCHAR(240),
    PRIMARY KEY (ESTADO)
);

CREATE TABLE PEDIDOS_X_PRODUCTOS ( 
    ID_PEDIDO INT,
    ID_PRODUCTO INT,
    CANTIDAD INT,
    PRIMARY KEY (ID_PEDIDO, ID_PRODUCTO)
    
);

CREATE TABLE PRODUCTOS ( 
    NOMBRE VARCHAR(60),
    DESCRIPCION VARCHAR(240),
    PRECIO INT,
    ID_PRODUCTO INT,
    PRIMARY KEY (ID_PRODUCTO)
);

CREATE TABLE HISTORIALES_ESTADOS ( 
    ID_RESERVA INT,
    ESTADO VARCHAR(20),
    FECHA_HORA_INICIO DATE,
    FECHA_HORA_FIN DATE,
    PRIMARY KEY (ID_RESERVA, ESTADO)
    
);

ALTER TABLE RESERVAS
	ADD CONSTRAINT FK_IDCLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE),
    ADD CONSTRAINT FK_IDPISTA FOREIGN KEY (ID_PISTA) REFERENCES PISTAS_BOWLING(ID_PISTA),
    ADD CONSTRAINT FK_IDPARTIDA FOREIGN KEY (ID_PARTIDA) REFERENCES PARTIDAS(ID_PARTIDA),
    ADD CONSTRAINT FK_IDPEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO);
    
ALTER TABLE HISTORIALES_ESTADOS
	ADD CONSTRAINT FK_IDRESERVA FOREIGN KEY (ID_RESERVA) REFERENCES RESERVAS(ID_RESERVA),
    ADD CONSTRAINT FK_ESTADO_RESERVA FOREIGN KEY (ESTADO) REFERENCES ESTADOS_RESERVAS(ESTADO);
    
ALTER TABLE PISTAS_BOWLING
    ADD CONSTRAINT FK_ESTADO_PISTA FOREIGN KEY (ESTADO) REFERENCES ESTADOS_PISTAS(ESTADO);
    
ALTER TABLE PARTIDAS
	ADD CONSTRAINT FK_IDPISTA2 FOREIGN KEY (ID_PISTA) REFERENCES PISTAS_BOWLING(ID_PISTA),
    ADD CONSTRAINT FK_ESTADOPARTIDA FOREIGN KEY (ESTADO) REFERENCES ESTADOS_PARTIDAS(ESTADO),
    ADD CONSTRAINT FK_IDRESERVA2 FOREIGN KEY (ID_RESERVA) REFERENCES RESERVAS(ID_RESERVA);
    
ALTER TABLE JUGADORES
    ADD CONSTRAINT FK_PARTIDAJUGADOR FOREIGN KEY (ID_PARTIDA) REFERENCES PARTIDAS(ID_PARTIDA);
    
ALTER TABLE TURNOS
    ADD CONSTRAINT FK_PARTIDATURNO FOREIGN KEY (ID_PARTIDA) REFERENCES PARTIDAS(ID_PARTIDA);
    
    
ALTER TABLE TIRADAS
	ADD CONSTRAINT FK_IDJUGADOR FOREIGN KEY (ID_JUGADOR) REFERENCES JUGADORES(ID_JUGADOR),
    ADD CONSTRAINT FK_NUMEROTURNO FOREIGN KEY (NUMERO_TURNO) REFERENCES TURNOS(NUMERO_TURNO);
    
ALTER TABLE PEDIDOS
	ADD CONSTRAINT FK_IDPRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO),
    ADD CONSTRAINT FK_ESTADO_PEDIDO FOREIGN KEY (ESTADO) REFERENCES ESTADOS_PEDIDOS(ESTADO);
    
ALTER TABLE PEDIDOS_X_PRODUCTOS
	ADD CONSTRAINT FK_IDPEDIDO2 FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO),
    ADD CONSTRAINT FK_IDPROD FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO);