# Generated by Django 5.1 on 2024-09-08 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_partida_estado_alter_pedido_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPartida',
            fields=[
                ('estado', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('estado', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoReserva',
            fields=[
                ('estado', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=240)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='jugador',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.producto'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='id_partida',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.partida'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='id_pedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.pedido'),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='id_reserva',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.reserva'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='id_partida',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.partida'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='id_pista',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.pistabowling'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='id_reserva',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.reserva'),
        ),
        migrations.AlterField(
            model_name='pedidoxproducto',
            name='id_pedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.pedido'),
        ),
        migrations.AlterField(
            model_name='pedidoxproducto',
            name='id_producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.producto'),
        ),
        migrations.AlterField(
            model_name='pistabowling',
            name='estado',
            field=models.ForeignKey(default='DISPONIBLE', on_delete=django.db.models.deletion.CASCADE, to='main.estadopista'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='id_cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.cliente'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='id_pista',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.pistabowling'),
        ),
        migrations.AlterField(
            model_name='tirada',
            name='id_jugador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.jugador'),
        ),
        migrations.AlterField(
            model_name='tirada',
            name='numero_turno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.turno'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='id_partida',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.partida'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='estado',
            field=models.ForeignKey(default='INICIADA', on_delete=django.db.models.deletion.CASCADE, to='main.estadopartida'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.ForeignKey(default='PENDIENTE', on_delete=django.db.models.deletion.CASCADE, to='main.estadopedido'),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='estado',
            field=models.ForeignKey(default='PENDIENTE', on_delete=django.db.models.deletion.CASCADE, to='main.estadoreserva'),
        ),
    ]
