# Generated by Django 5.1 on 2024-10-12 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_cliente_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='estado',
        ),
    ]
