# Generated by Django 5.1 on 2024-10-12 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_partida_cant_jugadores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='id_partida',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='id_pedido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_reserva',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.reserva'),
        ),
    ]
