# Generated by Django 5.1 on 2024-10-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_pistabowling_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialestado',
            name='fecha_hora_fin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='fecha_hora_inicio',
            field=models.DateTimeField(),
        ),
    ]
