# Generated by Django 5.1 on 2024-10-17 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_historialestado_fecha_hora_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='estado',
            field=models.ForeignKey(default='Disponible', on_delete=django.db.models.deletion.CASCADE, to='main.estadopartida'),
        ),
    ]
