# Generated by Django 5.1 on 2024-10-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_partida_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha_hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
