# Generated by Django 5.1.2 on 2024-11-09 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_cliente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='ganador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas_ganadas', to='main.jugador'),
        ),
    ]
